// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9A4yX-7J66etdhqr_igLy6c6jhXbJ9Io',
    appId: '1:328842559224:android:8bebcbbf0221a7d106c50d',
    messagingSenderId: '328842559224',
    projectId: 'disney-d2bd5',
    storageBucket: 'disney-d2bd5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2AQM-q6yb5pW7WE4NMYZHKUu9pN7YxXc',
    appId: '1:328842559224:ios:54f23af5b3ec1ec806c50d',
    messagingSenderId: '328842559224',
    projectId: 'disney-d2bd5',
    storageBucket: 'disney-d2bd5.firebasestorage.app',
    iosBundleId: 'com.algoriza.profedisneyNew',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsQEgA3xF4_Wso1ktlooyHBjlzJt4fgfM',
    appId: '1:328842559224:web:c767225192dc787b06c50d',
    messagingSenderId: '328842559224',
    projectId: 'disney-d2bd5',
    authDomain: 'disney-d2bd5.firebaseapp.com',
    storageBucket: 'disney-d2bd5.firebasestorage.app',
    measurementId: 'G-D7BVQY90NQ',
  );

}